<<<<<<< HEAD
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { Capacitor } from '@capacitor/core';
import { capacitorStorage } from '@/lib/capacitorStorage';
import type { Database } from './types';
=======
>>>>>>> ebb7643 (prep iOS rebuild – env, capacitor, deps)

import { createClient } from "@supabase/supabase-js";

<<<<<<< HEAD
// Detect if running on native platform (iOS/Android)
const isNative = Capacitor.isNativePlatform();

// Log platform detection for debugging
console.log('[Supabase Client] Platform:', Capacitor.getPlatform(), 'isNative:', isNative);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // Use Capacitor Preferences on native, localStorage on web
    storage: isNative ? capacitorStorage : localStorage,
    persistSession: true,
    autoRefreshToken: true,
    // Disable URL session detection on native - auth comes through deep links
    detectSessionInUrl: !isNative,
    // Use PKCE flow for better mobile security
    flowType: 'pkce',
  }
});
=======
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseAnonKey) {
  console.error("Supabase env vars missing", {
    supabaseUrl,
    supabaseAnonKey,
  });
  throw new Error("Supabase environment variables are missing");
}

export const supabase = createClient(
  supabaseUrl,
  supabaseAnonKey,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  }
);

>>>>>>> ebb7643 (prep iOS rebuild – env, capacitor, deps)
